# Server Configuration
server.port=8081

# Application Name
spring.application.name=auth-service

# PostgreSQL Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/livewave_auth
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Spring Data JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update

# SQL Logging for Development
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
